version: '3.3'
services:
  api:
    build: .
    environment:
      PORT: 3000
      HOST: mysql
      USER: root
      PASSWORD: root
    ports:
      - 3000:3000
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
